//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comics()
        {
            this.Rental_Comics = new HashSet<Rental_Comics>();
            this.Sold_Comics = new HashSet<Sold_Comics>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Series { get; set; }
        public string Publishing_house { get; set; }
        public string Written { get; set; }
        public Nullable<System.DateTime> Released_Date { get; set; }
        public int Rating_ID { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Selling_price { get; set; }
        public Nullable<int> Rental_price { get; set; }
    
        public virtual Rating_system Rating_system { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental_Comics> Rental_Comics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold_Comics> Sold_Comics { get; set; }
    }
}
