//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STRPO2Entities : DbContext
    {
        public STRPO2Entities()
            : base("name=STRPO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comics> Comics { get; set; }
        public virtual DbSet<Rating_system> Rating_system { get; set; }
        public virtual DbSet<Rental_Comics> Rental_Comics { get; set; }
        public virtual DbSet<Sold_Comics> Sold_Comics { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_type> User_type { get; set; }
    }
}
